### PR TITLE
Step 2 of public feed project: add a servlet file.

### PR DESCRIPTION
**Pull request by KevinWorkman**
This is a barebones file that prints out a hard-coded message for now. I'll add the logic in a follow-up PR.

I tested this by manually navigating to the /feed URL in a local server: https://i.imgur.com/NqIq0RS.png

### CODE REVIEW

**Comment by antara678** [comment]
Just to clarify, adding a servlet file creates a new feed. And for now your feed is just a hard coded message?

**Comment by KevinWorkman** [comment]
> Just to clarify, adding a servlet file creates a new feed. And for now your feed is just a hard coded message?

Yep, that's exactly right. In one of my follow-up CLs, this servlet will provide JSON data. For now it's just a hard-coded message.

**Review by antara678 — COMMENTED** [review]
Looks good!

**Review by antara678 — COMMENTED** [review]
Looks Good

**Review by antara678 — APPROVED** [review]
Looks great!

**Pull request merged**
